# Twitter API credentials. In productive environments, use helm-secrets plugin
twitterConsumerKey: Your_Consumer_Key
twitterConsumerSecret: Your_Consumer_Secret
twitterAccessToken: Your_Access_Token
twitterAccessSecret: Your_Access_Secret
