## Default values for raponchi.
## Deployment
appname: raponchi
# Resources allocation for Raponchi container
container:
  version: 0.1.5
  deployment:
    req:
      cpu: 100m
      mem: 256M
    lim:
      cpu: 150m
      mem: 300M
# User and group to run and mount storage
securityContext:
  runAsUser: 1001
  runAsGroup: 1001
## Application behaviour
# Log Level
logLevel: INFO
# Time Zone
timeZone: Europe/Berlin
# Frog Keyword
frogWord: rana
# Number of frog images to be retrieved
frogNumber: 5
# How frequently the scheduler will poll for pending jobs, in seconds
frogScheduleInternal: 3600
# Run scheduled job on start, useful in development environments
frogSchedulerNow: True
# Online source for frog names. Should be a URL to a plain text file with names, one per line.
frogNamesURL: https://raw.githubusercontent.com/olea/lemarios/master/nombres-propios-es.txt
# Temporary path where frog images will be stored.
frogPath: dataset
# Twitter API credentials. In productive environments, consider using helm-secrets plugin
twitterConsumerKey: Your_Consumer_Key
twitterConsumerSecret: Your_Consumer_Secret
twitterAccessToken: Your_Access_Token
twitterAccessSecret: Your_Access_Secret
