apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.runAsUser }}
      containers:
        - name: raponchi
          image: elautoestopista/raponchi:{{ .Values.container.version }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: {{ .Values.container.deployment.req.cpu }}
              memory: {{ .Values.container.deployment.req.mem }}
            limits:
              cpu: {{ .Values.container.deployment.lim.cpu }}
              memory: {{ .Values.container.deployment.lim.mem }}
          env:
          - name: TIMEZONE
            value: {{ .Values.timeZone | quote}}
          - name: FROGWORD
            value: {{ .Values.frogWord | quote }}
          - name: FROG_NUMBER
            value: {{ .Values.frogNumber | quote }}
          - name: FROG_SCHEDULER_INTERVAL
            value: {{ .Values.frogScheduleInternal | quote }}
          - name: FROG_SCHEDULER_RUN_NOW
            value: {{ .Values.frogSchedulerNow | quote }}
          - name: PATH_TO_FROGS
            value: /opt/raponchi/{{ .Values.frogPath }}
          - name: FROG_NAMES_URL
            value: {{ .Values.frogNamesURL | quote }}
          - name: LOGLEVEL
            value: {{ .Values.logLevel | quote }}
          - name: TW_CONSUMER_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appname }}-consumer-key
                key: token
          - name: TW_CONSUMER_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appname }}-consumer-secret
                key: token
          - name: TW_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appname }}-access-token
                key: token
          - name: TW_ACCESS_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appname }}-access-secret
                key: token
          volumeMounts:
            - name: {{ .Values.appname }}-storage
              mountPath: /opt/raponchi/{{ .Values.frogPath }}
      volumes:
        - name: {{ .Values.appname }}-storage
          persistentVolumeClaim:
            claimName: {{ .Values.appname }}-pvc
