apiVersion: v1
kind: PersistentVolume
metadata:
  name: raponchi-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/raponchi
  storageClassName: local-storage
