apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}-consumer-key
type: Opaque
data:
  token: {{ .Values.twitterConsumerKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}-consumer-secret
type: Opaque
data:
  token: {{ .Values.twitterConsumerSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}-access-token
type: Opaque
data:
  token: {{ .Values.twitterAccessToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}-access-secret
type: Opaque
data:
  token: {{ .Values.twitterAccessSecret }}
