apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}-consumer-key
type: Opaque
data:
  token: {{ .Values.twitterConsumerKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}-consumer-secret
type: Opaque
data:
  token: {{ .Values.twitterConsumerSecret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}-access-token
type: Opaque
data:
  token: {{ .Values.twitterAccessToken | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}-access-secret
type: Opaque
data:
  token: {{ .Values.twitterAccessSecret | b64enc | quote }}
