apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Value.appname }}-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: {{ .Value.localPersistentStoragePath }}
  storageClassName: local-storage
