{{ if eq .Values.serviceSchema "https" }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name:  {{ .Values.appName }}-redirect-https
  namespace: monitoring
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: "{{ .Values.serviceSchemaPort }}"
{{ end }}
