apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appName }}-prometheus-server
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/prometheus/
  storageClassName: local-storage
