# Default values for ygdrassil-monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
## Please note these are specific configurations for ygdrassil-monitoring package.
## You can use the values in all the dependencies charts.
## See https://artifacthub.io/packages/helm/prometheus-community/prometheus for more info
appName: ygdrassil-monitoring
# Decide expose services using TLS or not
serviceSchema: "http"
# HTTPS port when Schema is https
serviceSchemaPort: "443"
## Prometheus
prometheusUrl: prometheus.example.com
# External port of the Service, will redirect to 443 HTTPS if serviceSchema is set to https
prometheusPort: "80"
## Alertmanager
alertmanagerUrl: alertmanager.example.com
# External port of the Service, will redirect to 443 HTTPS if serviceSchema is set to https
alertmanagerPort: "80"
## Grafana
grafanaUrl: grafana.example.com
# External port of the Service, will redirect to 443 HTTPS if serviceSchema is set to https
grafanaPort: "80"
## OpenSearch
opensearch:
  persistence:
    enabled: false
  singleNode: true
# As Secrets
opensearch:
    extraEnvs:
      - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
        value: <your_cool_password>
      - name: DISABLE_INSTALL_DEMO_CONFIG
        value: "false"
      - name: DISABLE_SECURITY_PLUGIN
        value: "false"
opensearch-dashboards:
    extraEnvs:
        - name: DISABLE_INSTALL_DEMO_CONFIG
          value: "true"
        - name: DISABLE_SECURITY_PLUGIN
          value: "true"
