apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: kube-system
spec:
  redirectScheme:
    scheme: {{ .Values.middleware.scheme }}
    permanent: "true"
    port: {{ .Values.middleware.port }}
