name: Build, Package and Sign Helm packages in repository

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.HELM_SIGNING_KEY }}
          passphrase: ${{ secrets.HELM_SIGNING_PASS }}
          trust_level: 5

      - name: DEBUG show GPG keys
        run: gpg -K

      - name: Download and install Helm 3 lastest
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

#      - name: Lint Packages
#        run: helm lint helm/*

      - name: Build dependencies for AeneaBot
        run: helm dependencies build helm/aeneabot
      - name: Build dependencies for Raponchi
        run: helm dependencies build helm/raponchi
      - name: Build dependencies for Ygdrassil-monitoring
        run: helm dependencies build helm/ygdrassil-monitoring

#      - name: Package and Sign
#        run: echo $PASSPHRASE | helm secrets package --sign --key "Ygdrassil Sergio's Package Helm Signing Key" --keyring $GPG_PRIVATE_KEY --passphrase-file "-" helm/* --destination ygdrassil

#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v5
#        with:
#          commit-message: Add report file
#          title: '[Example] Add report file'
#          body: >
#            This PR is auto-generated by
#            [create-pull-request](https://github.com/peter-evans/create-pull-request).
#          labels: report, automated pr
