apiVersion: v2
name: aeneabot
version: 0.1.0
description: AeneaBot is a Telegram Chat Bot which includes its own conversational AI base in Ollama
type: application
keywords:
  - aeneabot
  - telegram
  - python
home: https://sergiofernandezcordero.github.io/ygdrassil
sources:
  - https://sergiofernandezcordero.github.io/helm/aeneabot
  - https://github.com/SergioFernandezCordero/AeneaBot
  - https://github.com/SergioFernandezCordero/AeneaAI
icon: https://sergiofernandezcordero.github.io/ygdrassil/images/aenea.png
maintainers:
  - name: Sergio Fernández Cordero
    email: sergio@fernandezcordero.net
    url: https://sergio.fernandezcordero.net
appVersion: 4.0.1
